// <auto-generated />
using System;
using ALo.Addresses.Data.SqLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ALo.Addresses.Data.SqLite.Migrations
{
    [DbContext(typeof(SqLiteFiasContext))]
    partial class SqLiteFiasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("ALo.Addresses.Data.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte>("ActualityStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("DivisionType")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(120);

                    b.Property<Guid?>("ParentAddressId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeShortName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("AddressId", "ActualityStatus");

                    b.HasIndex("ParentAddressId", "ActualityStatus");

                    b.ToTable("Addresses","dbo");
                });

            modelBuilder.Entity("ALo.Addresses.Data.Models.House", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildNumber")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<byte>("HouseState")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("HouseType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StructureNumber")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("AddressId", "EndDate");

                    b.HasIndex("HouseId", "EndDate");

                    b.ToTable("Houses","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
